import test from 'node:test';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:8787';
async function request(path,{method='GET',body,cookie,headers={}}={}){
  const res=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...headers},body:body?JSON.stringify(body):undefined});
  return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};
}
test('admin adjustments preserve daily visits, permissions and audit history',async()=>{
  await request('/api/setup',{method:'POST',headers:{'x-bootstrap-secret':'local-test-bootstrap'},body:{adminUsername:'admin_local',adminPassword:'Admin-test-928!',employeeUsername:'mostrador_local',employeePassword:'Staff-test-928!'}});
  const admin=await request('/api/login/staff',{method:'POST',body:{username:'admin_local',password:'Admin-test-928!'}});
  const staff=await request('/api/login/staff',{method:'POST',body:{username:'mostrador_local',password:'Staff-test-928!'}});
  assert.equal(admin.status,200);
  const client=await request('/api/register',{method:'POST',body:{name:'Ajustes de prueba',phone:'662'+String(Date.now()).slice(-7),pin:'4826'}});
  assert.equal(client.status,201);
  const card=await request('/api/card',{cookie:client.cookie});
  const path='/api/admin/customers/'+client.data.user.id+'/stamps';
  const adjust=(body,cookie=admin.cookie)=>request(path,{method:'POST',cookie,body});
  const movement=(expectedStamps,delta,extra={})=>({expectedStamps,delta,reason:'Corrección de prueba',...extra});
  assert.equal((await adjust(movement(0,1),staff.cookie)).status,403);
  assert.equal((await adjust(movement(0,1),client.cookie)).status,403);
  assert.equal((await adjust(movement(0,1),null)).status,401);
  assert.equal((await adjust(movement(0,-1))).status,400);
  assert.equal((await adjust(movement(0,1,{reason:'x'}))).status,400);
  assert.equal((await request(path,{method:'POST',cookie:admin.cookie,headers:{origin:'https://example.com'},body:movement(0,1)})).status,403);
  const stamp=()=>request('/api/staff/stamp',{method:'POST',cookie:staff.cookie,body:{cardId:card.data.card.id}});
  assert.equal((await stamp()).status,200);
  assert.equal((await adjust(movement(0,1))).status,409);
  const removed=await adjust(movement(1,-1,{cancelToday:true}));
  assert.equal(removed.status,200);
  assert.equal(removed.data.card.stamps,0);
  assert.equal(removed.data.card.canStampToday,true);
  assert.equal((await stamp()).status,200);
  assert.equal((await stamp()).status,409);
  const plainRemove=await adjust(movement(1,-1));
  assert.equal(plainRemove.status,200);
  assert.equal(plainRemove.data.card.canStampToday,false);
  assert.equal((await stamp()).status,409);
  const concurrent=await Promise.all([adjust(movement(0,1)),adjust(movement(0,1))]);
  assert.deepEqual(concurrent.map(result=>result.status).sort(),[200,409]);
  for(let balance=1;balance<9;balance++)assert.equal((await adjust(movement(balance,1))).status,200);
  assert.equal((await adjust(movement(9,1))).status,400);
  const reward=await request('/api/card',{cookie:client.cookie});
  assert.equal(reward.data.card.stamps,9);
  assert.equal((await adjust(movement(9,-1))).data.card.stamps,8);
  assert.equal((await request('/api/staff/redeem',{method:'POST',cookie:staff.cookie,body:{cardId:card.data.card.id}})).status,409);
  assert.equal((await adjust(movement(8,1))).status,200);
  assert.equal((await request('/api/staff/redeem',{method:'POST',cookie:staff.cookie,body:{cardId:card.data.card.id}})).status,200);
  assert.equal((await adjust(movement(9,-1))).status,409);
  const dashboard=await request('/api/admin/dashboard?eventPerPage=100',{cookie:admin.cookie});
  assert.equal(dashboard.status,200);
  assert.ok(dashboard.data.events.some(e=>e.card_id===card.data.card.id&&e.event_type==='stamp_voided'));
  assert.ok(dashboard.data.events.some(e=>e.card_id===card.data.card.id&&e.event_type==='stamp_removed'&&e.reason==='Corrección de prueba'));
  assert.ok(dashboard.data.events.some(e=>e.card_id===card.data.card.id&&e.event_type==='stamp_added'));
  const filtered=await request('/api/admin/dashboard?eventType=stamp_voided&eventCustomer=Ajustes%20de%20prueba',{cookie:admin.cookie});
  assert.ok(filtered.data.events.length>0);
  assert.ok(filtered.data.events.every(event=>event.event_type==='stamp_voided'&&event.customer.includes('Ajustes de prueba')));
});
