import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createServer} from 'node:http';
import {chromium} from 'file:///C:/Users/ferha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import worker,{testables} from '../worker/index.js';
import {TENANTS,resolveTenant} from '../worker/tenants.js';

const message='Estamos realizando una actualización breve. Intenta nuevamente en unos minutos.';
const english='We’re performing a brief update. Please try again in a few minutes.';
const slugs=['renace','mooncoffee','santofe','vainillacoffee'];
const routes=['/api','/api/me','/api/register','/api/setup','/api/login/customer','/api/login/staff','/api/logout','/api/card','/api/account/secret','/api/card/preferences','/api/staff/card?value=TEST','/api/staff/stamp','/api/staff/redeem','/api/staff/customers/test/pin','/api/admin/dashboard','/api/admin/export/clients','/api/admin/export/activity','/api/admin/employees','/api/admin/employees/test','/api/admin/customers/test','/api/admin/customers/test/pin','/api/admin/customers/test/stamps','/api/admin/demo-customers/reset','/api/future-operation','/renace/api/me'];
const methods=['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'];
const assets={async fetch(request){const path=new URL(request.url).pathname;try{const file=new URL('../public'+(path==='/'?'/index.html':path),import.meta.url);const type=path==='/'?'text/html':path.endsWith('.js')?'application/javascript':path.endsWith('.css')?'text/css':path.endsWith('.svg')?'image/svg+xml':path.endsWith('.jpg')?'image/jpeg':path.endsWith('.png')?'image/png':'application/octet-stream';return new Response(readFileSync(file),{headers:{'content-type':type}});}catch{return new Response('',{status:404});}}};
function schema(migrated=true){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).sort().filter(n=>migrated||n<'0013'))db.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));return db;}
function binding(db,counter={queries:0}){return{prepare(sql){counter.queries++;let args=[];const statement={bind(...values){args=values;return statement;},async first(column){const row=db.prepare(sql).get(...args);return column?row?.[column]??null:row??null;},async all(){return{results:db.prepare(sql).all(...args)};},async run(){const result=db.prepare(sql).run(...args);return{success:true,meta:{changes:Number(result.changes),last_row_id:Number(result.lastInsertRowid)}};}};return statement;},async batch(statements){db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}};}
function environment(db,slug='santofe',mode='OFF',counter){return{DB:binding(db,counter),ASSETS:assets,DEV_TENANT:slug,MAINTENANCE_MODE:mode,SESSION_DAYS:'30',APP_TIMEZONE:'America/Tijuana'};}
async function invoke(env,path,body,cookie){const response=await worker.fetch(new Request('http://127.0.0.1'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined}),env);return{status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};}
async function fixtures(db,slug){const env=environment(db,slug),password='Local-only-'+crypto.randomUUID(),secret=await testables.hashSecret(password);for(const role of ['employee','admin'])db.prepare('INSERT INTO users(id,business_id,role,name,username,secret_hash,secret_salt) VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(),'business_'+slug,role,'Maintenance local '+role,'maintenance_'+role+'_'+slug,secret.hash,secret.salt);const customer=await invoke(env,'/api/register',{name:'Maintenance local customer',phone:'000008000'+slugs.indexOf(slug),pin:'4826'});assert.equal(customer.status,201);const staff=await invoke(env,'/api/login/staff',{username:'maintenance_employee_'+slug,password}),admin=await invoke(env,'/api/login/staff',{username:'maintenance_admin_'+slug,password});assert.equal(staff.status,200);assert.equal(admin.status,200);return{customer,staff,admin,card:(await invoke(env,'/api/card',null,customer.cookie)).data.card};}
function addVainilla(db){db.exec("INSERT INTO businesses(id,slug,name,reward_goal,reward_name,timezone,active,stamp_policy) VALUES('business_vainillacoffee','vainillacoffee','Vainilla Coffee',9,'Bebida gratis','America/Tijuana',1,'per_item')");}

test('Maintenance guard blocks every API method before even reading D1, including legacy aliases and invalid configuration',async()=>{
 for(const slug of slugs){let dbReads=0;const env={DEV_TENANT:slug,MAINTENANCE_MODE:'ON',get DB(){dbReads++;throw Error('D1 must not be accessed');}};
  for(const method of methods)for(const path of routes){const result=await worker.fetch(new Request('http://127.0.0.1'+path,{method,headers:{cookie:'loyalty_session=existing-session'}}),env);assert.equal(result.status,503,slug+' '+method+' '+path);assert.equal(result.headers.get('retry-after'),'300');assert.equal(result.headers.get('cache-control'),'no-store');assert.equal(result.headers.get('set-cookie'),null);assert.deepEqual(await result.json(),{ok:false,error:{code:'maintenance',message}});}assert.equal(dbReads,0);
 }
 for(const mode of ['on',' ON ','invalid',''])assert.equal((await worker.fetch(new Request('https://app.haloswebs.com/renace/api/me'),{MAINTENANCE_MODE:mode})).status,503);
 // No network header or request payload can bypass the flag.
 assert.equal((await worker.fetch(new Request('https://santofe.haloswebs.com/api/setup',{method:'POST',headers:{'x-bootstrap-secret':'anything','x-maintenance-mode':'OFF'},body:'{}'}),{MAINTENANCE_MODE:'ON'})).status,503);
});

test('NEW Worker serves public shell/PWA on OLD and NEW schemas while maintenance APIs execute zero SQL',async()=>{
 for(const migrated of [false,true]){const db=schema(migrated),counter={queries:0};try{
  assert.equal(db.prepare('PRAGMA table_info(loyalty_cards)').all().some(c=>c.name==='rewards_pending'),migrated);
  for(const slug of slugs){const env=environment(db,slug,'ON',counter);for(const path of ['/','/assets/live.js','/assets/i18n.js','/assets/tenant.css','/assets/tenant.js','/manifest.webmanifest','/service-worker.js',TENANTS[slug].logo,...TENANTS[slug].pwaIcons.map(i=>i.src)])assert.equal((await worker.fetch(new Request('http://127.0.0.1'+path),env)).status,200,slug+' '+path);for(const path of routes)assert.equal((await invoke(env,path)).status,503);}
  assert.equal(counter.queries,0);
 }finally{db.close();}}
});

test('Maintenance suspends scheduled cleanup before D1 access; OFF and missing flag retain normal cleanup',async()=>{
 let reads=0,scheduled=0;for(const mode of ['ON','invalid'])await worker.scheduled({}, {MAINTENANCE_MODE:mode,get DB(){reads++;throw Error('No scheduled D1 access');}}, {waitUntil(){scheduled++;}});assert.equal(reads,0);assert.equal(scheduled,0);
 const db=schema();try{for(const mode of ['OFF',undefined]){const counter={queries:0},pending=[];await worker.scheduled({},environment(db,'renace',mode,counter),{waitUntil(p){pending.push(p);}});await Promise.all(pending);assert.equal(pending.length,1);assert.ok(counter.queries>=2);}}finally{db.close();}
});

test('NEW schema maintenance OFF retains authentication, tenant-safe QR, purchases, explicit rewards, Admin and exports for all four tenants',async()=>{
 const db=schema();addVainilla(db);try{const records=[];for(const slug of slugs){const f=await fixtures(db,slug),env=environment(db,slug),perItem=TENANTS[slug].stampPolicy==='per_item';records.push({slug,f});assert.equal((await invoke(env,'/api/me',null,f.customer.cookie)).data.user.role,'customer');assert.equal((await invoke(env,'/api/staff/card?value='+encodeURIComponent(f.card.qrValue),null,f.staff.cookie)).status,200);const bought=await invoke(env,'/api/staff/stamp',{cardId:f.card.id,quantity:perItem?TENANTS[slug].rewardGoal+3:1,expectedVersion:f.card.rewardVersion,operationId:crypto.randomUUID()},f.staff.cookie);assert.equal(bought.status,200);if(perItem){assert.equal(bought.data.card.stamps,3);assert.equal(bought.data.card.rewardsPending,0);assert.equal(bought.data.card.rewardChoicesPending,1);const saved=await invoke(env,'/api/staff/reward-choice',{cardId:f.card.id,decision:'save',expectedVersion:bought.data.card.rewardVersion,operationId:crypto.randomUUID()},f.staff.cookie);assert.equal(saved.status,200);const redeemed=await invoke(env,'/api/staff/redeem',{cardId:f.card.id,expectedVersion:saved.data.card.rewardVersion,operationId:crypto.randomUUID()},f.staff.cookie);assert.equal(redeemed.status,200);assert.equal(redeemed.data.card.stamps,3);assert.equal(redeemed.data.card.rewardsPending,0);}else{assert.equal(bought.data.card.stamps,1);assert.equal((await invoke(env,'/api/staff/stamp',{cardId:f.card.id},f.staff.cookie)).status,409);}for(const path of ['/api/admin/dashboard','/api/admin/export/clients','/api/admin/export/activity'])assert.equal((await invoke(env,path,null,f.admin.cookie)).status,200);}
 for(const {slug,f}of records){const other=records.find(r=>r.slug!==slug);assert.equal((await invoke(environment(db,slug),'/api/staff/card?value='+encodeURIComponent(other.f.card.qrValue),null,f.staff.cookie)).status,404);}
 assert.equal(resolveTenant(new URL('https://vainillacoffee.haloswebs.com'),{}).slug,'vainillacoffee');
 }finally{db.close();}
});

test('Frontend maintenance preserves sessions/forms and protected route on startup, translates ES/EN, pauses polling and recovers only on manual retry',async t=>{
 const db=schema();addVainilla(db);t.after(()=>db.close());const f=await fixtures(db,'vainillacoffee'),counter={queries:0};let mode='ON',apiRequests=0;
 const server=createServer(async(req,res)=>{try{const chunks=[];for await(const c of req)chunks.push(c);if(req.url.startsWith('/api/'))apiRequests++;const response=await worker.fetch(new Request('http://127.0.0.1'+req.url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body:Buffer.concat(chunks)})}),environment(db,'vainillacoffee',mode,counter));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const [name,value]=f.customer.cookie.split('=');await context.addCookies([{name,value,url:base,secure:false}]);
 await page.goto(base+'/#tarjeta');await page.waitForSelector('#app-loader',{state:'detached'});await page.waitForSelector('[data-maintenance]');assert.equal(new URL(page.url()).hash,'#tarjeta');assert.equal(counter.queries,0);assert.equal((await context.cookies()).find(c=>c.name===name)?.value,value);
 await page.evaluate(()=>window.LoyaltyI18n.set('en'));assert.ok((await page.locator('[data-maintenance]').innerText()).includes(english));await page.evaluate(()=>window.LoyaltyI18n.set('es'));assert.ok((await page.locator('[data-maintenance]').innerText()).includes(message));
 mode='OFF';await page.click('#maintenance-retry');await page.waitForSelector('#qr svg',{state:'attached'});assert.equal((await context.cookies()).find(c=>c.name===name)?.value,value);
 await page.clock.install();mode='ON';const queries=counter.queries;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForSelector('[data-maintenance]');assert.equal(await page.locator('#qr svg').count(),1);assert.equal(counter.queries,queries);const requests=apiRequests;await page.clock.runFor(60000);assert.equal(apiRequests,requests,'no automatic polling/retry loop');await page.click('#logout');assert.equal(new URL(page.url()).hash,'#tarjeta');assert.equal(await page.locator('#card-link').isVisible(),true);assert.equal((await context.cookies()).find(c=>c.name===name)?.value,value);
 mode='OFF';await page.click('#maintenance-retry');await page.waitForSelector('#qr svg',{state:'attached'});assert.equal(await page.locator('[data-maintenance]').count(),0);
 // Register/login keep typed fields, report maintenance rather than invalid credentials.
 mode='ON';await page.goto(base+'/?auth-test#registro');await page.waitForSelector('#auth-form');await page.fill('[name="name"]','Local test');await page.fill('[name="login"]','0000088888');await page.fill('[name="secret"]','4826');await page.evaluate(()=>window.LoyaltyI18n.set('en'));await page.click('#auth-form button');await page.waitForFunction(m=>document.querySelector('#error')?.textContent===m,english);await page.evaluate(()=>window.LoyaltyI18n.set('es'));assert.equal(await page.locator('#error').innerText(),message);assert.equal(await page.inputValue('[name="login"]'),'0000088888');assert.equal((await context.cookies()).find(c=>c.name===name)?.value,value);
 for(const [role,route]of [['staff','empleado'],['admin','admin']]){await context.clearCookies();const [n,v]=f[role].cookie.split('=');await context.addCookies([{name:n,value:v,url:base,secure:false}]);await page.goto(base+'/?role='+role+'#'+route);await page.waitForSelector('[data-maintenance]');assert.equal(new URL(page.url()).hash,'#'+route);mode='OFF';await page.click('#maintenance-retry');await page.waitForSelector(role==='staff'?'#lookup':'#export-events');mode='ON';const before=counter.queries;if(role==='staff'){await page.fill('#lookup input','0000080003');await page.click('#lookup button');}else await page.click('#export-events');await page.waitForSelector('[data-maintenance]');assert.equal(counter.queries,before);assert.equal((await context.cookies()).find(c=>c.name===n)?.value,v);}
 assert.deepEqual(errors,[]);await context.close();
});
