import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import ExcelJS from 'exceljs';
import {chromium} from 'file:///C:/Users/ferha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {schema,fixture,invoke,action,server,slugs} from './reward-choice-fixture.mjs';
const sizes=[[360,800],[390,844],[393,852],[412,915],[1366,768],[1440,900]];
const evidence=process.env.REWARD_DECISIONS_EVIDENCE;
async function screenshot(page,name,selector){if(!evidence)return;mkdirSync(evidence,{recursive:true});await page.waitForSelector('#app-loader',{state:'detached'});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.LoyaltyI18n.set('es'));if(selector)await page.locator(selector).screenshot({path:evidence+'/'+name+'.png'});else await page.screenshot({path:evidence+'/'+name+'.png',fullPage:true});}
async function fit(page){for(const [width,height]of sizes){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'horizontal overflow '+width);}}
async function download(page,selector){const pending=page.waitForEvent('download');await page.click(selector);const d=await pending,parts=[];for await(const part of await d.createReadStream())parts.push(part);return Buffer.concat(parts);}

test('Per-item client and staff show full earned cards, mandatory bilingual choices, real progress after saving, responsive Admin/activity and real XLSX/PNG QR',async t=>{
 const db=schema(),browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>db.close());t.after(()=>browser.close());
 for(const slug of ['vainillacoffee','santofe']){
  const f=await fixture(db,slug);await action(db,f,'stamp',{quantity:8});await action(db,f,'stamp',{quantity:slug==='vainillacoffee'?4:5});
  const host=await server(db,slug);t.after(()=>new Promise(r=>host.app.close(r)));const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  async function view(cookie,route){await context.clearCookies();const [name,value]=cookie.split('=');await context.addCookies([{name,value,url:host.base}]);await page.goto(host.base+'/?testRole='+crypto.randomUUID()+'#'+route);await page.waitForSelector('#app-loader',{state:'detached'});await page.evaluate(()=>window.LoyaltyI18n.set('es'));}
  async function scanned(){await page.fill('#lookup input',f.phone);await page.click('#lookup button');await page.waitForSelector('#reward-save');}
  await view(f.customer.cookie,'tarjeta');await page.waitForSelector('#qr svg',{state:'attached'});const earned=slug==='vainillacoffee'?'.vainilla-flower-slot.is-earned':'.santofe-card-stamps .filled';assert.equal(await page.locator(earned).count(),f.card.goal);assert.equal(await page.locator('.reward-choice-count').innerText(),'1');assert.equal(await page.locator('.reward-count').innerText(),'0');assert.equal(await page.locator('#reward-save').count(),0);
  await fit(page);if(slug==='vainillacoffee'){const faces=await page.locator('.loyalty-card-face').evaluateAll(ns=>ns.map(n=>[n.offsetWidth,n.offsetHeight]));assert.deepEqual(faces[0],faces[1]);}
  await screenshot(page,slug==='vainillacoffee'?'01-vainilla-completo-por-decidir':'04-santofe-completa-por-decidir');
  await page.evaluate(()=>window.LoyaltyI18n.set('en'));assert.match(await page.locator('.reward-decision').innerText(),/At the counter|Rewards awaiting decision/);
  const png=await download(page,'#download-card');const decoded=await page.evaluate(async encoded=>{const img=new Image();img.src='data:image/png;base64,'+encoded;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height);return jsQR(pixels.data,c.width,c.height)?.data;},png.toString('base64'));assert.equal(decoded,f.card.qrValue);
  await view(f.staff.cookie,'empleado');await scanned();assert.equal(await page.locator('#stamp').isDisabled(),true);assert.equal(await page.locator('#stamp-plus').isDisabled(),true);assert.equal(await page.locator('#stamp-minus').isDisabled(),true);assert.match(await page.locator('.reward-balance').innerText(),new RegExp('3/'+f.card.goal));
  for(const selector of ['#reward-save','#reward-redeem-now'])assert.ok(await page.locator(selector).evaluate(n=>n.getBoundingClientRect().height>=44));
  await fit(page);await page.reload();await page.waitForSelector('#lookup');await scanned();assert.equal(await page.locator('#stamp').isDisabled(),true);await screenshot(page,slug==='vainillacoffee'?'02-vainilla-mostradordecision':'05-santofe-mostradordecision','#staff-card');
  await page.evaluate(()=>window.LoyaltyI18n.set('en'));assert.equal(await page.locator('#reward-save').innerText(),'Save for later');assert.equal(await page.locator('#reward-redeem-now').innerText(),'Redeem now');let confirm='';page.once('dialog',d=>{confirm=d.message();return d.accept();});await page.click('#reward-save');await page.waitForFunction(()=>document.querySelector('#stamp')&&!document.querySelector('#stamp').disabled);assert.match(confirm,/resolves one reward/);assert.equal(await page.locator('#redeem').isEnabled(),true);assert.equal(await page.locator(slug==='vainillacoffee'?earned:'#staff-card .stamp.filled').count(),3);
  f.card=(await invoke(db,slug,'/api/card',{cookie:f.customer.cookie})).data.card;assert.equal(f.card.stamps,3);assert.equal(f.card.rewardChoicesPending,0);assert.equal(f.card.rewardsPending,1);
  await view(f.customer.cookie,'tarjeta');assert.equal(await page.locator(earned).count(),3);assert.equal(await page.locator('.reward-count').innerText(),'1');if(slug==='vainillacoffee')await screenshot(page,'03-vainilla-guardada-progreso-real');
  if(slug==='vainillacoffee'){
   await page.goto(host.base+'/#cuenta');await page.waitForSelector('#profile-form');await page.fill('#profile-form input','Fer Local');await page.fill('[name="currentSecret"]','4826');await page.evaluate(()=>window.LoyaltyI18n.set('en'));assert.equal(await page.inputValue('#profile-form input'),'Fer Local');await page.evaluate(()=>window.LoyaltyI18n.set('es'));await screenshot(page,'06-mi-cuenta-editando-nombre');
   await page.click('#profile-form button');await page.waitForFunction(()=>document.querySelector('[data-account-name]')?.textContent==='Fer Local');assert.equal(await page.inputValue('[name="currentSecret"]'),'4826');
   await action(db,f,'stamp',{quantity:9});await view(f.admin.cookie,'admin');await page.fill('#customer-search input','Fer Local');await page.click('#customer-search button');await page.waitForFunction(()=>document.querySelectorAll('.customers-panel tbody tr').length===1);await fit(page);const client=await page.locator('.customers-panel tbody').innerText();assert.match(client,/Fer Local/);assert.match(client,/3\/9/);assert.equal(await page.locator('td[data-label="Recompensas por decidir"]').innerText(),'1');assert.equal(await page.locator('td[data-label="Bebidas gratis disponibles"]').innerText(),'1');await screenshot(page,'07-admin-tres-saldos','.customers-panel');
   await page.fill('[name="eventCustomer"]','Fer Local');await page.click('#event-filters button[type="submit"],#event-filters button:not([type])');await page.waitForFunction(()=>document.querySelectorAll('.activity-customer').length>0&&[...document.querySelectorAll('.activity-customer')].every(n=>n.textContent.includes('Fer Local')));await screenshot(page,'08-actividad-nombre-actual-celular','.activity-panel');assert.match(await page.locator('.activity-phone').first().innerText(),/700/);
   await page.evaluate(()=>window.LoyaltyI18n.set('en'));const clients=new ExcelJS.Workbook();await clients.xlsx.load(await download(page,'#export-customers'));const sheet=clients.worksheets[0];assert.equal(sheet.getCell(4,10).value,'Free drinks available');assert.equal(sheet.getCell(4,11).value,'Rewards awaiting decision');assert.equal(sheet.getCell(5,1).value,'Fer Local');assert.equal(sheet.getCell(5,4).value,3);assert.equal(sheet.getCell(5,10).value,1);assert.equal(sheet.getCell(5,11).value,1);
   const activity=new ExcelJS.Workbook();await activity.xlsx.load(await download(page,'#export-events'));const rows=activity.worksheets.flatMap(s=>s.getRows(5,s.rowCount-4)||[]);assert.ok(rows.some(r=>r.getCell(3).value==='Fer Local'&&r.getCell(4).value===f.phone&&r.getCell(5).value==='Reward saved'));assert.ok(rows.some(r=>String(r.getCell(6).value).includes('awaiting decision')));
  }
  if(slug==='santofe'){
   await action(db,f,'stamp',{quantity:f.card.goal});await view(f.staff.cookie,'empleado');await scanned();await page.evaluate(()=>window.LoyaltyI18n.set('en'));page.once('dialog',d=>d.accept());await page.click('#reward-redeem-now');await page.waitForFunction(()=>document.querySelector('#stamp')&&!document.querySelector('#stamp').disabled);
   const redeemed=(await invoke(db,slug,'/api/card',{cookie:f.customer.cookie})).data.card;assert.equal(redeemed.stamps,3);assert.equal(redeemed.rewardsPending,1);assert.equal(redeemed.rewardChoicesPending,0);assert.equal(redeemed.redeemed,1);
  }
  assert.deepEqual(errors,[]);await context.close();
 }
});

test('Customer account name editing works across all four tenants without losing language, PIN draft, card QR, balance or session',async t=>{
 const db=schema(),browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>db.close());t.after(()=>browser.close());
 for(const slug of slugs){const f=await fixture(db,slug),host=await server(db,slug);t.after(()=>new Promise(r=>host.app.close(r)));const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage();const [name,value]=f.customer.cookie.split('=');await context.addCookies([{name,value,url:host.base}]);await page.goto(host.base+'/#cuenta');await page.waitForSelector('#profile-form');await page.waitForSelector('#app-loader',{state:'detached'});await page.fill('#profile-form input','  Ana María  ');await page.fill('[name="currentSecret"]','4826');
  await page.evaluate(()=>window.LoyaltyI18n.set('en'));assert.equal(await page.inputValue('#profile-form input'),'  Ana María  ');assert.equal(await page.locator('#profile-form button').innerText(),'Save name');await page.click('#profile-form button');await page.waitForFunction(()=>document.querySelector('[data-account-name]')?.textContent==='Ana María');assert.equal(await page.inputValue('[name="currentSecret"]'),'4826');assert.equal((await context.cookies()).find(c=>c.name===name)?.value,value);await fit(page);
  await page.goto(host.base+'/#tarjeta');await page.waitForSelector('#qr svg',{state:'attached'});assert.match(await page.locator('.personal-card').innerText(),/Ana María/);const card=(await invoke(db,slug,'/api/card',{cookie:f.customer.cookie})).data.card;assert.equal(card.qrValue,f.card.qrValue);assert.equal(card.stamps,0);await context.close();
 }
});
