import { test } from 'node:test';
import assert from 'node:assert/strict';
import qrcode from 'qrcode-generator';
import jsQR from 'jsqr';
import { randomBytes } from 'node:crypto';
test('personal QR generated by the page decodes with the camera fallback',()=>{
  const value=`hermanitos:v1:${randomBytes(32).toString('base64url')}`;
  const qr=qrcode(0,'M');qr.addData(value);qr.make();
  const scale=7,margin=4,n=qr.getModuleCount(),width=(n+margin*2)*scale;
  const pixels=new Uint8ClampedArray(width*width*4);
  for(let y=0;y<width;y++)for(let x=0;x<width;x++){
    const row=Math.floor(y/scale)-margin,col=Math.floor(x/scale)-margin;
    const v=row>=0&&row<n&&col>=0&&col<n&&qr.isDark(row,col)?0:255;
    const i=(y*width+x)*4;pixels[i]=pixels[i+1]=pixels[i+2]=v;pixels[i+3]=255;
  }
  assert.equal(jsQR(pixels,width,width).data,value);
});
